### ISSUE TITLE
Adopt pre-release extension support

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-typescript-next#25]
These docs have all the details, also feel free to reach out if you have any questions
https://github.com/microsoft/vscode-docs/blob/vnext/api/working-with-extensions/publishing-extension.md#pre-release-extensions

**Comment by mjbvz** [comment]
Thanks for the info @isidorn!

This extension is a little odd since it simply provides a build of typescript that VS Code's built-in TypeScript extension can consume. The extension is not functional on its own

I'm also not convinced this extension should have a published pre-release build since the extension is implicitly always shipping pre-release code. We don't want to ship a stable version of TypeScript with this extension, especially not as a default

So I feel that is that this extension is a special case but please let me know if you disagree or think there's another way we could improve the UX here

**Comment by isidorn** [comment]
@mjbvz you are right. This one is a bit special since the release version is built in.
So I agree let's keep this closed and thanks for the informatino.
